/*
 * Anno Amsterdam CoreAPI
 * The internal API for the Anno Amsterdam project's CMS
 *
 * The version of the OpenAPI document: v1
 * Contact: preis@computer.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package nl.anno.amsterdam.api;

import nl.anno.amsterdam.ApiException;
import nl.anno.amsterdam.model.Audioguide;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for AudioguidesApi
 */
@Ignore
public class AudioguidesApiTest {

    private final AudioguidesApi api = new AudioguidesApi();

    
    /**
     * 
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void audioguidesCreateTest() throws ApiException {
        Audioguide data = null;
                Audioguide response = api.audioguidesCreate(data);
        // TODO: test validations
    }
    
    /**
     * 
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void audioguidesDeleteTest() throws ApiException {
        String id = null;
                api.audioguidesDelete(id);
        // TODO: test validations
    }
    
    /**
     * 
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void audioguidesListTest() throws ApiException {
                List<Audioguide> response = api.audioguidesList();
        // TODO: test validations
    }
    
    /**
     * 
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void audioguidesPartialUpdateTest() throws ApiException {
        String id = null;
        Audioguide data = null;
                Audioguide response = api.audioguidesPartialUpdate(id, data);
        // TODO: test validations
    }
    
    /**
     * 
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void audioguidesReadTest() throws ApiException {
        String id = null;
                Audioguide response = api.audioguidesRead(id);
        // TODO: test validations
    }
    
    /**
     * 
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void audioguidesUpdateTest() throws ApiException {
        String id = null;
        Audioguide data = null;
                Audioguide response = api.audioguidesUpdate(id, data);
        // TODO: test validations
    }
    
}
